package size_test

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/corygyarmathy/afk-agent/internal/size"
)

// repo is a repository with one commit, and base is that commit. Each test adds
// its own changes on top, and measures them.
func repo(t *testing.T, files map[string]string) (dir, base string) {
	t.Helper()
	for k, v := range map[string]string{
		"GIT_AUTHOR_NAME": "afk", "GIT_AUTHOR_EMAIL": "afk@example.invalid",
		"GIT_COMMITTER_NAME": "afk", "GIT_COMMITTER_EMAIL": "afk@example.invalid",
		"GIT_CONFIG_GLOBAL": os.DevNull, "GIT_CONFIG_NOSYSTEM": "1",
	} {
		t.Setenv(k, v)
	}
	dir = t.TempDir()
	git(t, dir, "init", "--quiet", "--initial-branch=main")
	files["README"] = "readme\n"
	write(t, dir, files)
	return dir, commitAll(t, dir)
}

func git(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v: %s", args, err, out)
	}
	return strings.TrimSpace(string(out))
}

func write(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	for name, body := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func commitAll(t *testing.T, dir string) string {
	t.Helper()
	git(t, dir, "add", "--all")
	git(t, dir, "commit", "--quiet", "--allow-empty", "-m", "change")
	return git(t, dir, "rev-parse", "HEAD")
}

// lines is n lines of text.
func lines(n int) string {
	var b strings.Builder
	for i := range n {
		fmt.Fprintf(&b, "line %d\n", i)
	}
	return b.String()
}

func measure(t *testing.T, dir, base, head string) size.Count {
	t.Helper()
	c, err := size.Measure(context.Background(), dir, base, head)
	if err != nil {
		t.Fatal(err)
	}
	return c
}

// Changed lines are added and removed lines both, and tests are counted beside
// them rather than in them.
func TestChangedLinesAreCountedAndTestsApart(t *testing.T) {
	dir, base := repo(t, map[string]string{"main.go": lines(10)})
	write(t, dir, map[string]string{
		"main.go":                    strings.Replace(lines(10), "line 5\n", "changed\n", 1) + "new\n",
		"job.go":                     lines(7),
		"job_test.go":                lines(4),
		"internal/x/testdata/in.txt": lines(3),
	})
	head := commitAll(t, dir)

	// main.go: one line changed (one removed, one added) and one added.
	if got, want := measure(t, dir, base, head), (size.Count{Lines: 3 + 7, Tests: 4 + 3}); got != want {
		t.Errorf("count = %+v, want %+v", got, want)
	}
}

// Each exclusion is left out of the count, and out of the test count too.
func TestExcludedFilesAreNotCounted(t *testing.T) {
	for _, tc := range []struct {
		name  string
		files map[string]string
	}{
		{"vendored", map[string]string{"vendor/example.com/m/m.go": lines(50)}},
		{"vendored, deeper", map[string]string{"web/node_modules/pkg/index.js": lines(50)}},
		{"third party", map[string]string{"third_party/lib/lib.c": lines(50)}},
		{"a lock file", map[string]string{"flake.lock": lines(50)}},
		{"go.sum", map[string]string{"go.sum": lines(50)}},
		{"a package lock", map[string]string{"web/package-lock.json": lines(50)}},
		{"a Cargo lock", map[string]string{"Cargo.lock": lines(50)}},
		{"a generated Go file", map[string]string{"api/api.pb.go": "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n" + lines(50)}},
		{"marked generated", map[string]string{".gitattributes": "", "schema.sql": lines(50)}},
		{"marked vendored", map[string]string{".gitattributes": "", "lib/jquery.js": lines(50)}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			attrs := ""
			if _, ok := tc.files[".gitattributes"]; ok {
				attrs = "schema.sql linguist-generated\nlib/** linguist-vendored\n"
			}
			dir, base := repo(t, map[string]string{".gitattributes": attrs})
			files := map[string]string{}
			for name, body := range tc.files {
				if name != ".gitattributes" {
					files[name] = body
				}
			}
			write(t, dir, files)
			head := commitAll(t, dir)
			if got := measure(t, dir, base, head); got != (size.Count{}) {
				t.Errorf("count = %+v, want nothing counted", got)
			}
		})
	}
}

// A file deleted whole is not counted: deleting code is not what a reviewer
// spends a sitting on. A file cut down is, by the lines it lost.
func TestAWholeFileDeletionIsNotCounted(t *testing.T) {
	dir, base := repo(t, map[string]string{"old.go": lines(300), "old_test.go": lines(200), "kept.go": lines(10)})
	git(t, dir, "rm", "--quiet", "old.go", "old_test.go")
	write(t, dir, map[string]string{"kept.go": lines(4)})
	head := commitAll(t, dir)

	if got, want := measure(t, dir, base, head), (size.Count{Lines: 6}); got != want {
		t.Errorf("count = %+v, want %+v", got, want)
	}
}

// A file moved and not changed is no lines to review.
func TestARenameIsCountedByWhatChanged(t *testing.T) {
	dir, base := repo(t, map[string]string{"a/job.go": lines(100)})
	if err := os.Mkdir(filepath.Join(dir, "b"), 0o755); err != nil {
		t.Fatal(err)
	}
	git(t, dir, "mv", "a/job.go", "b/job.go")
	head := commitAll(t, dir)

	if got := measure(t, dir, base, head); got != (size.Count{}) {
		t.Errorf("count = %+v, want nothing for a pure rename", got)
	}
}

// An attribute set false takes back an exclusion a convention made: the
// repository says the file is its own.
func TestAnAttributeSetFalseCountsTheFileAgain(t *testing.T) {
	dir, base := repo(t, map[string]string{".gitattributes": "vendor/ours/** -linguist-vendored\n"})
	write(t, dir, map[string]string{"vendor/ours/ours.go": lines(12)})
	head := commitAll(t, dir)

	if got, want := measure(t, dir, base, head), (size.Count{Lines: 12}); got != want {
		t.Errorf("count = %+v, want %+v", got, want)
	}
}

// The measure reads the commits, not the checkout: it works in a bare
// repository, where the push is made from.
func TestTheMeasureReadsABareRepository(t *testing.T) {
	dir, base := repo(t, map[string]string{".gitattributes": "gen.txt linguist-generated\n"})
	write(t, dir, map[string]string{"gen.txt": lines(40), "real.go": lines(9)})
	head := commitAll(t, dir)
	bare := filepath.Join(t.TempDir(), "bare.git")
	git(t, "", "clone", "--quiet", "--bare", dir, bare)

	if got, want := measure(t, bare, base, head), (size.Count{Lines: 9}); got != want {
		t.Errorf("count = %+v, want %+v", got, want)
	}
}

func TestOverIsStrictlyMoreThanTheSignal(t *testing.T) {
	for _, tc := range []struct {
		lines, tests, signal int
		want                 bool
	}{
		{400, 0, 400, false},
		{401, 0, 400, true},
		{10, 5000, 400, false},
	} {
		if got := (size.Count{Lines: tc.lines, Tests: tc.tests}).Over(tc.signal); got != tc.want {
			t.Errorf("Count{%d, %d}.Over(%d) = %v, want %v", tc.lines, tc.tests, tc.signal, got, tc.want)
		}
	}
}
